build:
    dependencies:
        override:
            - composer self-update
            - composer install --ignore-platform-reqs --no-interaction --no-scripts

    environment:
        php:
            version: 7.2
            ini:
                'date.timezone': 'Europe/Amsterdam'
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false

    project_setup:
        override: true
    nodes:
        analysis:
            tests:
                override:
                    - make php_linting
    tests:
        override:
            - command: './vendor/bin/phpunit -c phpunit.xml'

    resources:
        cpus: 1

    root_path: './'

    cache:
        disabled: false
        directories:
            - vendor/
            - ~/.composer/

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'node_modules/*'
        - 'vendor/*'
        - 'scripts/*'
