build:
    dependencies:
        override:
            - composer self-update
            - composer install --ignore-platform-reqs --no-interaction --no-scripts

    environment:
        php:
            version: 7.2
            ini:
                'date.timezone': 'Europe/Amsterdam'
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
        variables:
            DOCKER: 'false'

    project_setup:
        override: true
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - make php_lint
        tests_1:
            tests:
                override:
                    - command: make test_unit
                      coverage:
                        file: tests/coverage.xml
                        format: clover

    resources:
        cpus: 1

    root_path: './'

    cache:
        disabled: false
        directories:
            - vendor/
            - ~/.composer/

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'node_modules/*'
        - 'vendor/*'
        - 'scripts/*'
