# https://github.com/akhomy/docker-compose-lamp
version: "3.5"

services:
    site_api_php:
        build: ./docker/images/php-fpm
        container_name: site_api_php
        image: site_api_php
        networks:
            - site_api_network
        volumes:
            - ./:/var/www/
        working_dir: /var/www

    site_api_web:
        build: ./docker/images/apache/
        container_name: site_api_web
        image: site_api_web
        depends_on:
            - site_api_php
        networks:
            - site_api_network
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
        working_dir: /var/www

    #    mailhog:
#        image: mailhog/mailhog
#        container_name: mailhog
#        networks:
#            - site_api_network
#        ports:
#            - "8025:8025"

    site_api_mysql:
        build: ./docker/images/mysql
        container_name: site_api_mysql
        image: site_api_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
            MYSQL_DATABASE: web_db
        networks:
            - site_api_network
        ports:
            - "3306:3306"
        volumes:
            - ./docker/data/mysql:/var/lib/mysql

networks:
    site_api_network:
        name: site_api_network

