#!/bin/bash
echo "DROP DATABASE IF EXISTS web_db;" | mysql -h 127.0.0.1 -u"root" -p"123"
echo "CREATE DATABASE web_db;" | mysql -h 127.0.0.1 -u"root" -p"123"

flyway -configFiles=etc/database/flyway.conf migrate
